### ISSUE TITLE
Override existing tmux windows 

### ISSUE THREAD

**Issue by mpailloncy** [nwknu/tmux-ssh-handler#2]
I use tmux with some windows initialized (with https://github.com/tmuxinator/tmuxinator).
When I launch a "ssh://..." link, all current windows are overriden by 2 tmux windows : a "local" and the ssh link windows.

So, the script works, but not as expected for me :-)

**Comment by aanc** [comment]
Hello @mpapo 

It is the expected behaviour. Maybe we could close the "local" window so it's cleaner, i'll look into that.
